formatting:
  active: true
  android: false
  autoCorrect: true
  FinalNewline:
    active: true
    autoCorrect: true
  NoWildcardImports:
    active: true
    autoCorrect: true
style:
  active: true
  NewLineAtEndOfFile:
    active: false