version: '3.1'

services:
  elasticsearch_1:
    image: elasticsearch:7.6.1
    container_name: elasticsearch_collaborative_1
    environment:
      - node.name=node1
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=node2,node3
      - cluster.initial_master_nodes=node1,node2,node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      ports:
        - 9200:9200
      networks:
        - elastic
  elasticsearch_2:
    image: elasticsearch:7.6.1
    container_name: elasticsearch_collaborative_2
    environment:
      - node.name=node2
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=node1,node3
      - cluster.initial_master_nodes=node1,node2,node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      networks:
        - elastic
  elasticsearch_3:
    image: elasticsearch:7.6.1
    container_name: elasticsearch_collaborative_3
    environment:
      - node.name=node3
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=node2,node1
      - cluster.initial_master_nodes=node1,node2,node3
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
        memlock:
          soft: -1
          hard: -1
      networks:
        - elastic
  mysql:
    image: mysql:5.7.26
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: localEnv
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: localEnv
    volumes:
        - ./local-env/database:/docker-entrypoint-initdb.d
  toxiproxy:
    container_name: toxiproxy
    build: ./local-env/resilience-testing/toxiproxy
    links:
      - "redis:redis"
    ports:
      - "7379:6379"
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "8474"]
      interval: 2s
      timeout: 5s
      retries: 3

networks:
  elasticsearch:
    drive: bridge
