spring:
  jmx:
    enabled: true

console_plain_text_logging_encoder: false

management:
  server:
    port: 8080
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-details: always
    metrics:
      enabled: true
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, metrics
      base-path: /actuator
  metrics:
    use-global-registry: true
    export:
      statsd:
        enabled: false
        host: ""
        port: 8125
        step: 1m